/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedSystemCheckRouteImport } from './routes/_authenticated/system-check'
import { Route as AuthenticatedHotelGroupsRouteImport } from './routes/_authenticated/hotel-groups'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedSalesIndexRouteImport } from './routes/_authenticated/sales.index'
import { Route as AuthenticatedQuotesIndexRouteImport } from './routes/_authenticated/quotes.index'
import { Route as AuthenticatedPackagesIndexRouteImport } from './routes/_authenticated/packages.index'
import { Route as AuthenticatedHotelsIndexRouteImport } from './routes/_authenticated/hotels.index'
import { Route as AuthenticatedQuotesNewRouteImport } from './routes/_authenticated/quotes.new'
import { Route as AuthenticatedQuotesIdRouteImport } from './routes/_authenticated/quotes.$id'
import { Route as AuthenticatedPackagesIdRouteImport } from './routes/_authenticated/packages.$id'
import { Route as AuthenticatedHotelsIdRouteImport } from './routes/_authenticated/hotels.$id'
import { Route as AuthenticatedDebugFlowCheckRouteImport } from './routes/_authenticated/debug.flow-check'
import { Route as AuthenticatedDebugDataFlowRouteImport } from './routes/_authenticated/debug.data-flow'
import { Route as AuthenticatedSalesPackagesIdRouteImport } from './routes/_authenticated/sales.packages.$id'
import { Route as AuthenticatedRatesMatrixNewRouteImport } from './routes/_authenticated/rates.matrix.new'
import { Route as AuthenticatedPackagesIdAddRatesRouteImport } from './routes/_authenticated/packages.$id.add-rates'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemCheckRoute =
  AuthenticatedSystemCheckRouteImport.update({
    id: '/system-check',
    path: '/system-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelGroupsRoute =
  AuthenticatedHotelGroupsRouteImport.update({
    id: '/hotel-groups',
    path: '/hotel-groups',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSalesIndexRoute = AuthenticatedSalesIndexRouteImport.update({
  id: '/sales/',
  path: '/sales/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesIndexRoute =
  AuthenticatedQuotesIndexRouteImport.update({
    id: '/quotes/',
    path: '/quotes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPackagesIndexRoute =
  AuthenticatedPackagesIndexRouteImport.update({
    id: '/packages/',
    path: '/packages/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotelsIndexRoute =
  AuthenticatedHotelsIndexRouteImport.update({
    id: '/hotels/',
    path: '/hotels/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedQuotesNewRoute = AuthenticatedQuotesNewRouteImport.update({
  id: '/quotes/new',
  path: '/quotes/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesIdRoute = AuthenticatedQuotesIdRouteImport.update({
  id: '/quotes/$id',
  path: '/quotes/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPackagesIdRoute = AuthenticatedPackagesIdRouteImport.update({
  id: '/packages/$id',
  path: '/packages/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHotelsIdRoute = AuthenticatedHotelsIdRouteImport.update({
  id: '/hotels/$id',
  path: '/hotels/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebugFlowCheckRoute =
  AuthenticatedDebugFlowCheckRouteImport.update({
    id: '/debug/flow-check',
    path: '/debug/flow-check',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebugDataFlowRoute =
  AuthenticatedDebugDataFlowRouteImport.update({
    id: '/debug/data-flow',
    path: '/debug/data-flow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSalesPackagesIdRoute =
  AuthenticatedSalesPackagesIdRouteImport.update({
    id: '/sales/packages/$id',
    path: '/sales/packages/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRatesMatrixNewRoute =
  AuthenticatedRatesMatrixNewRouteImport.update({
    id: '/rates/matrix/new',
    path: '/rates/matrix/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPackagesIdAddRatesRoute =
  AuthenticatedPackagesIdAddRatesRouteImport.update({
    id: '/add-rates',
    path: '/add-rates',
    getParentRoute: () => AuthenticatedPackagesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hotel-groups': typeof AuthenticatedHotelGroupsRoute
  '/system-check': typeof AuthenticatedSystemCheckRoute
  '/users': typeof AuthenticatedUsersRoute
  '/debug/data-flow': typeof AuthenticatedDebugDataFlowRoute
  '/debug/flow-check': typeof AuthenticatedDebugFlowCheckRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/packages/$id': typeof AuthenticatedPackagesIdRouteWithChildren
  '/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/hotels/': typeof AuthenticatedHotelsIndexRoute
  '/packages/': typeof AuthenticatedPackagesIndexRoute
  '/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/sales/': typeof AuthenticatedSalesIndexRoute
  '/packages/$id/add-rates': typeof AuthenticatedPackagesIdAddRatesRoute
  '/rates/matrix/new': typeof AuthenticatedRatesMatrixNewRoute
  '/sales/packages/$id': typeof AuthenticatedSalesPackagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/hotel-groups': typeof AuthenticatedHotelGroupsRoute
  '/system-check': typeof AuthenticatedSystemCheckRoute
  '/users': typeof AuthenticatedUsersRoute
  '/debug/data-flow': typeof AuthenticatedDebugDataFlowRoute
  '/debug/flow-check': typeof AuthenticatedDebugFlowCheckRoute
  '/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/packages/$id': typeof AuthenticatedPackagesIdRouteWithChildren
  '/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/hotels': typeof AuthenticatedHotelsIndexRoute
  '/packages': typeof AuthenticatedPackagesIndexRoute
  '/quotes': typeof AuthenticatedQuotesIndexRoute
  '/sales': typeof AuthenticatedSalesIndexRoute
  '/packages/$id/add-rates': typeof AuthenticatedPackagesIdAddRatesRoute
  '/rates/matrix/new': typeof AuthenticatedRatesMatrixNewRoute
  '/sales/packages/$id': typeof AuthenticatedSalesPackagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/hotel-groups': typeof AuthenticatedHotelGroupsRoute
  '/_authenticated/system-check': typeof AuthenticatedSystemCheckRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/debug/data-flow': typeof AuthenticatedDebugDataFlowRoute
  '/_authenticated/debug/flow-check': typeof AuthenticatedDebugFlowCheckRoute
  '/_authenticated/hotels/$id': typeof AuthenticatedHotelsIdRoute
  '/_authenticated/packages/$id': typeof AuthenticatedPackagesIdRouteWithChildren
  '/_authenticated/quotes/$id': typeof AuthenticatedQuotesIdRoute
  '/_authenticated/quotes/new': typeof AuthenticatedQuotesNewRoute
  '/_authenticated/hotels/': typeof AuthenticatedHotelsIndexRoute
  '/_authenticated/packages/': typeof AuthenticatedPackagesIndexRoute
  '/_authenticated/quotes/': typeof AuthenticatedQuotesIndexRoute
  '/_authenticated/sales/': typeof AuthenticatedSalesIndexRoute
  '/_authenticated/packages/$id/add-rates': typeof AuthenticatedPackagesIdAddRatesRoute
  '/_authenticated/rates/matrix/new': typeof AuthenticatedRatesMatrixNewRoute
  '/_authenticated/sales/packages/$id': typeof AuthenticatedSalesPackagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/hotel-groups'
    | '/system-check'
    | '/users'
    | '/debug/data-flow'
    | '/debug/flow-check'
    | '/hotels/$id'
    | '/packages/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/hotels/'
    | '/packages/'
    | '/quotes/'
    | '/sales/'
    | '/packages/$id/add-rates'
    | '/rates/matrix/new'
    | '/sales/packages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/hotel-groups'
    | '/system-check'
    | '/users'
    | '/debug/data-flow'
    | '/debug/flow-check'
    | '/hotels/$id'
    | '/packages/$id'
    | '/quotes/$id'
    | '/quotes/new'
    | '/hotels'
    | '/packages'
    | '/quotes'
    | '/sales'
    | '/packages/$id/add-rates'
    | '/rates/matrix/new'
    | '/sales/packages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/hotel-groups'
    | '/_authenticated/system-check'
    | '/_authenticated/users'
    | '/_authenticated/debug/data-flow'
    | '/_authenticated/debug/flow-check'
    | '/_authenticated/hotels/$id'
    | '/_authenticated/packages/$id'
    | '/_authenticated/quotes/$id'
    | '/_authenticated/quotes/new'
    | '/_authenticated/hotels/'
    | '/_authenticated/packages/'
    | '/_authenticated/quotes/'
    | '/_authenticated/sales/'
    | '/_authenticated/packages/$id/add-rates'
    | '/_authenticated/rates/matrix/new'
    | '/_authenticated/sales/packages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-check': {
      id: '/_authenticated/system-check'
      path: '/system-check'
      fullPath: '/system-check'
      preLoaderRoute: typeof AuthenticatedSystemCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotel-groups': {
      id: '/_authenticated/hotel-groups'
      path: '/hotel-groups'
      fullPath: '/hotel-groups'
      preLoaderRoute: typeof AuthenticatedHotelGroupsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/': {
      id: '/_authenticated/sales/'
      path: '/sales'
      fullPath: '/sales/'
      preLoaderRoute: typeof AuthenticatedSalesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/': {
      id: '/_authenticated/quotes/'
      path: '/quotes'
      fullPath: '/quotes/'
      preLoaderRoute: typeof AuthenticatedQuotesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages/': {
      id: '/_authenticated/packages/'
      path: '/packages'
      fullPath: '/packages/'
      preLoaderRoute: typeof AuthenticatedPackagesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/': {
      id: '/_authenticated/hotels/'
      path: '/hotels'
      fullPath: '/hotels/'
      preLoaderRoute: typeof AuthenticatedHotelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/new': {
      id: '/_authenticated/quotes/new'
      path: '/quotes/new'
      fullPath: '/quotes/new'
      preLoaderRoute: typeof AuthenticatedQuotesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes/$id': {
      id: '/_authenticated/quotes/$id'
      path: '/quotes/$id'
      fullPath: '/quotes/$id'
      preLoaderRoute: typeof AuthenticatedQuotesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages/$id': {
      id: '/_authenticated/packages/$id'
      path: '/packages/$id'
      fullPath: '/packages/$id'
      preLoaderRoute: typeof AuthenticatedPackagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotels/$id': {
      id: '/_authenticated/hotels/$id'
      path: '/hotels/$id'
      fullPath: '/hotels/$id'
      preLoaderRoute: typeof AuthenticatedHotelsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/flow-check': {
      id: '/_authenticated/debug/flow-check'
      path: '/debug/flow-check'
      fullPath: '/debug/flow-check'
      preLoaderRoute: typeof AuthenticatedDebugFlowCheckRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debug/data-flow': {
      id: '/_authenticated/debug/data-flow'
      path: '/debug/data-flow'
      fullPath: '/debug/data-flow'
      preLoaderRoute: typeof AuthenticatedDebugDataFlowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sales/packages/$id': {
      id: '/_authenticated/sales/packages/$id'
      path: '/sales/packages/$id'
      fullPath: '/sales/packages/$id'
      preLoaderRoute: typeof AuthenticatedSalesPackagesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rates/matrix/new': {
      id: '/_authenticated/rates/matrix/new'
      path: '/rates/matrix/new'
      fullPath: '/rates/matrix/new'
      preLoaderRoute: typeof AuthenticatedRatesMatrixNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/packages/$id/add-rates': {
      id: '/_authenticated/packages/$id/add-rates'
      path: '/add-rates'
      fullPath: '/packages/$id/add-rates'
      preLoaderRoute: typeof AuthenticatedPackagesIdAddRatesRouteImport
      parentRoute: typeof AuthenticatedPackagesIdRoute
    }
  }
}

interface AuthenticatedPackagesIdRouteChildren {
  AuthenticatedPackagesIdAddRatesRoute: typeof AuthenticatedPackagesIdAddRatesRoute
}

const AuthenticatedPackagesIdRouteChildren: AuthenticatedPackagesIdRouteChildren =
  {
    AuthenticatedPackagesIdAddRatesRoute: AuthenticatedPackagesIdAddRatesRoute,
  }

const AuthenticatedPackagesIdRouteWithChildren =
  AuthenticatedPackagesIdRoute._addFileChildren(
    AuthenticatedPackagesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedHotelGroupsRoute: typeof AuthenticatedHotelGroupsRoute
  AuthenticatedSystemCheckRoute: typeof AuthenticatedSystemCheckRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedDebugDataFlowRoute: typeof AuthenticatedDebugDataFlowRoute
  AuthenticatedDebugFlowCheckRoute: typeof AuthenticatedDebugFlowCheckRoute
  AuthenticatedHotelsIdRoute: typeof AuthenticatedHotelsIdRoute
  AuthenticatedPackagesIdRoute: typeof AuthenticatedPackagesIdRouteWithChildren
  AuthenticatedQuotesIdRoute: typeof AuthenticatedQuotesIdRoute
  AuthenticatedQuotesNewRoute: typeof AuthenticatedQuotesNewRoute
  AuthenticatedHotelsIndexRoute: typeof AuthenticatedHotelsIndexRoute
  AuthenticatedPackagesIndexRoute: typeof AuthenticatedPackagesIndexRoute
  AuthenticatedQuotesIndexRoute: typeof AuthenticatedQuotesIndexRoute
  AuthenticatedSalesIndexRoute: typeof AuthenticatedSalesIndexRoute
  AuthenticatedRatesMatrixNewRoute: typeof AuthenticatedRatesMatrixNewRoute
  AuthenticatedSalesPackagesIdRoute: typeof AuthenticatedSalesPackagesIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedHotelGroupsRoute: AuthenticatedHotelGroupsRoute,
  AuthenticatedSystemCheckRoute: AuthenticatedSystemCheckRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedDebugDataFlowRoute: AuthenticatedDebugDataFlowRoute,
  AuthenticatedDebugFlowCheckRoute: AuthenticatedDebugFlowCheckRoute,
  AuthenticatedHotelsIdRoute: AuthenticatedHotelsIdRoute,
  AuthenticatedPackagesIdRoute: AuthenticatedPackagesIdRouteWithChildren,
  AuthenticatedQuotesIdRoute: AuthenticatedQuotesIdRoute,
  AuthenticatedQuotesNewRoute: AuthenticatedQuotesNewRoute,
  AuthenticatedHotelsIndexRoute: AuthenticatedHotelsIndexRoute,
  AuthenticatedPackagesIndexRoute: AuthenticatedPackagesIndexRoute,
  AuthenticatedQuotesIndexRoute: AuthenticatedQuotesIndexRoute,
  AuthenticatedSalesIndexRoute: AuthenticatedSalesIndexRoute,
  AuthenticatedRatesMatrixNewRoute: AuthenticatedRatesMatrixNewRoute,
  AuthenticatedSalesPackagesIdRoute: AuthenticatedSalesPackagesIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
